### ISSUE TITLE
New blog post

### ISSUE THREAD

**Issue by bitaccountants** [minpeter/minpeter.xyz#8]
Whats happens when we add blog post in production - do we need to build and deploy again for the post to render and appear in post list? if not can this be automated ?

**Comment by minpeter** [comment]
Just create a new *.mdx file in a new commit and deploy it. Vercel will handle the rest.

**Comment by minpeter** [comment]
Is this a sufficient answer? If not, feel free to ask additional questions.

**Comment by bitaccountants** [comment]
> Is this a sufficient answer? If not, feel free to ask additional questions.

Thank you.

**Comment by bitaccountants** [comment]
Thank you.
